name: capstone_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  theme:
    path: theme

  cupertino_icons: ^1.0.2
  shared_preferences:
  curved_navigation_bar:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_analytics:
  flutter_bloc:
  flutter_native_splash:
  get_it:
  flutter_svg:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/splashscreen/logo.png
  background_image: assets/splashscreen/bgsplashscreen.png
  background_image_dark: assets/splashscreen/bgsplashscreen_dark.png
  image_dark: assets/splashscreen/logo_dark.png
  android_12:
    image: assets/splashscreen/logo.png
    image_dark: assets/splashscreen/logo_dark.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/coupon.svg
    - assets/icon/upload.svg
    - assets/icon/map-marker.svg
    - assets/icon/tokopedia.svg
    - assets/icon/shopee.svg
    - assets/icon/twitter.svg
    - assets/icon/facebook.svg
    - assets/icon/google.svg
    - assets/icon/check.svg
    - assets/icon/uncheck.svg
    - assets/icon/back.svg
    - assets/icon/menu.svg
    - assets/icon/cross.svg
    - assets/icon/user_outline.svg
    - assets/icon/user.svg
    - assets/icon/star_outline.svg
    - assets/icon/star.svg
    - assets/icon/home_outline.svg
    - assets/icon/home.svg
    - assets/icon/copy_outline.svg
    - assets/icon/copy.svg
    - assets/icon/lock.svg
    - assets/icon/eye.svg
    - assets/icon/eye-slash.svg
    - assets/icon/envelope.svg
    - assets/icon/envelope-fill.svg
    - assets/icon/pen.svg
    - assets/icon/pen-Light.svg
    - assets/icon/shield.svg
    - assets/icon/check-circle.svg
    - assets/icon/file.svg
    - assets/icon/bell.svg
    - assets/icon/bell-Light.svg
    - assets/icon/trash-Light.svg
    - assets/icon/camera-Light.svg
    - assets/icon/info-circle.svg
    - assets/icon/question-circle.svg
    - assets/icon/plus-circle.svg
    - assets/icon/settings.svg
    - assets/icon/globe.svg
    - assets/icon/mode.svg
    - assets/icon/log-out.svg
    - assets/icon/chevron-right.svg
    - assets/logo/logo.png
    - assets/logo/logo_dark.png
    - assets/image/gedung_sate.png
    - assets/image/gd-sate.png
    - assets/image/gd-sate-profile.png
    - assets/image/404.svg
    - assets/image/profile.jpg
