name: capstone_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  theme:
    path: theme

  cupertino_icons: ^1.0.2
  shared_preferences:
  curved_navigation_bar:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_analytics:
  flutter_bloc:
  flutter_native_splash:
  get_it:
  flutter_svg:
  equatable:
  image_picker:
  photo_view: 
  path_provider: 
  timelines: 
  intl:
  webview_flutter:
  page_transition:
  loading_animation_widget:
  cached_network_image: 
  pull_to_refresh: 
  http: ^0.13.4
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  flutter_slidable: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/splashscreen/logo.png
  background_image: assets/splashscreen/bgsplashscreen.png
  background_image_dark: assets/splashscreen/bgsplashscreen_dark.png
  image_dark: assets/splashscreen/logo_dark.png
  android_12:
    image: assets/splashscreen/logo.png
    image_dark: assets/splashscreen/logo_dark.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/bold/map.svg
    - assets/icon/bold/menu.svg
    - assets/icon/bold/copy.svg
    - assets/icon/bold/home.svg
    - assets/icon/bold/star.svg
    - assets/icon/bold/user.svg
    - assets/icon/bold/bell.svg
    - assets/icon/bold/clock.svg
    - assets/icon/bold/heart.svg
    - assets/icon/bold/file.svg
    - assets/icon/bold/settings.svg
    - assets/icon/bold/info-circle.svg
    - assets/icon/bold/log-out.svg
    - assets/icon/bold/question-circle.svg
    - assets/icon/bold/chevron-right.svg
    - assets/icon/bold/plus-square.svg
    - assets/icon/bold/check-circle.svg
    - assets/icon/bold/chevron-circle-down.svg
    - assets/icon/bold/chevron-circle-up.svg
    - assets/icon/bold/exclamation-circle.svg
    - assets/icon/bold/map-marker.svg
    - assets/icon/fill/map-marker.svg
    - assets/icon/fill/file.svg
    - assets/icon/fill/settings.svg
    - assets/icon/fill/info-circle.svg
    - assets/icon/fill/log-out.svg
    - assets/icon/fill/question-circle.svg
    - assets/icon/fill/chevron-right.svg
    - assets/icon/fill/train.svg
    - assets/icon/fill/user.svg
    - assets/icon/fill/star.svg
    - assets/icon/fill/home.svg
    - assets/icon/fill/copy.svg
    - assets/icon/fill/bell.svg
    - assets/icon/fill/clock.svg
    - assets/icon/fill/heart.svg
    - assets/icon/fill/exclamation-circle.svg
    - assets/icon/fill/plus-square.svg
    - assets/icon/fill/check-circle.svg
    - assets/icon/fill/chevron-circle-down.svg
    - assets/icon/fill/chevron-circle-up.svg
    - assets/icon/light/user.svg
    - assets/icon/light/star.svg
    - assets/icon/light/home.svg
    - assets/icon/light/copy.svg
    - assets/icon/light/bell.svg
    - assets/icon/light/clock.svg
    - assets/icon/light/heart.svg
    - assets/icon/light/file.svg
    - assets/icon/light/settings.svg
    - assets/icon/light/info-circle.svg
    - assets/icon/light/chevron-right.svg
    - assets/icon/light/log-out.svg
    - assets/icon/light/question-circle.svg
    - assets/icon/light/exclamation-circle.svg
    - assets/icon/light/map-marker.svg
    - assets/icon/light/check-circle.svg
    - assets/icon/light/chevron-circle-down.svg
    - assets/icon/light/chevron-circle-up.svg
    - assets/icon/light/plus-square.svg
    - assets/icon/regular/user.svg
    - assets/icon/regular/star.svg
    - assets/icon/regular/home.svg
    - assets/icon/regular/copy.svg
    - assets/icon/regular/map.svg
    - assets/icon/regular/menu.svg
    - assets/icon/regular/bell.svg
    - assets/icon/regular/clock.svg
    - assets/icon/regular/heart.svg
    - assets/icon/regular/file.svg
    - assets/icon/regular/settings.svg
    - assets/icon/regular/info-circle.svg
    - assets/icon/regular/log-out.svg
    - assets/icon/regular/question-circle.svg
    - assets/icon/regular/exclamation-circle.svg
    - assets/icon/regular/chevron-right.svg
    - assets/icon/regular/plus-square.svg
    - assets/icon/regular/times-square.svg
    - assets/icon/regular/chevron-down.svg
    - assets/icon/regular/map-marker.svg
    - assets/icon/regular/check-circle.svg
    - assets/icon/regular/chevron-circle-down.svg
    - assets/icon/regular/chevron-circle-up.svg
    - assets/icon/menu/icon-bus.png
    - assets/icon/menu/icon-news.png
    - assets/icon/menu/icon-tour.png
    - assets/icon/menu/icon-umkm.png
    - assets/icon/menu/icon-bus-dark.png
    - assets/icon/menu/icon-news-dark.png
    - assets/icon/menu/icon-tour-dark.png
    - assets/icon/menu/icon-umkm-dark.png
    - assets/icon/coupon.svg
    - assets/icon/upload.svg
    - assets/icon/map-marker.svg
    - assets/icon/tokopedia.svg
    - assets/icon/shopee.svg
    - assets/icon/twitter.svg
    - assets/icon/facebook.svg
    - assets/icon/google.svg
    - assets/icon/check.svg
    - assets/icon/uncheck.svg
    - assets/icon/back.svg
    - assets/icon/menu.svg
    - assets/icon/cross.svg
    - assets/icon/user_outline.svg
    - assets/icon/user.svg
    - assets/icon/star_outline.svg
    - assets/icon/star.svg
    - assets/icon/home_outline.svg
    - assets/icon/home.svg
    - assets/icon/copy_outline.svg
    - assets/icon/copy.svg
    - assets/icon/lock.svg
    - assets/icon/eye.svg
    - assets/icon/eye-slash.svg
    - assets/icon/envelope.svg
    - assets/icon/envelope-fill.svg
    - assets/icon/pen.svg
    - assets/icon/pen-Light.svg
    - assets/icon/shield.svg
    - assets/icon/check-circle.svg
    - assets/icon/file.svg
    - assets/icon/bell.svg
    - assets/icon/bell-Light.svg
    - assets/icon/trash-Light.svg
    - assets/icon/camera-Light.svg
    - assets/icon/info-circle.svg
    - assets/icon/question-circle.svg
    - assets/icon/plus-circle.svg
    - assets/icon/settings.svg
    - assets/icon/globe.svg
    - assets/icon/mode.svg
    - assets/icon/log-out.svg
    - assets/icon/chevron-right.svg
    - assets/logo/logo.png
    - assets/logo/logo_dark.png
    - assets/image/gedung_sate.png
    - assets/image/gd-sate.png
    - assets/image/gd-sate-profile.png
    - assets/image/404.svg
    - assets/image/profile.jpg
    - assets/image/hero-tour.png
    - assets/image/hero-craft.png
    - assets/image/hero-news.png
    - assets/image/hero-transport.png
    - assets/splashscreen/logo.png
    - assets/icon/bell-Bold.svg
    - assets/icon/news.png
    - assets/icon/transport.png
    - assets/icon/umkm.png
    - assets/icon/wisata.png
    - assets/splashscreen/image6.png
    - assets/splashscreen/image1.webp
    - assets/splashscreen/logo_dark.png
    - assets/splashscreen/map.jpg
    - assets/icon/bell.svg
    - assets/icon/star.svg
    - assets/icon/star_outline.svg
    - assets/icon/map.svg
    - assets/icon/search.svg
