name: capstone_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  theme:
    path: theme

  cupertino_icons: ^1.0.2
  shared_preferences:
  curved_navigation_bar:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_analytics:
  flutter_bloc:
  flutter_native_splash:
  get_it:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/splashscreen/logo.png
  background_image: assets/splashscreen/bgsplashscreen.png
  background_image_dark: assets/splashscreen/bgsplashscreen_dark.png
  image_dark: assets/splashscreen/logo_dark.png
  android_12:
    image: assets/splashscreen/logo.png
    image_dark: assets/splashscreen/logo_dark.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/coupon.svg
    - assets/icon/upload.svg
    - assets/icon/map-marker.svg
    - assets/icon/tokopedia.svg
    - assets/icon/shopee.svg
    - assets/icon/twitter.svg
    - assets/icon/facebook.svg
    - assets/icon/google.svg
