name: capstone_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  theme:
    path: theme

  cupertino_icons: ^1.0.2
  shared_preferences:
  curved_navigation_bar:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_analytics:
  flutter_bloc:
  flutter_native_splash:
  get_it:
  flutter_svg:
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  flutter_slidable: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/splashscreen/logo.png
  background_image: assets/splashscreen/bgsplashscreen.png
  background_image_dark: assets/splashscreen/bgsplashscreen_dark.png
  image_dark: assets/splashscreen/logo_dark.png
  android_12:
    image: assets/splashscreen/logo.png
    image_dark: assets/splashscreen/logo_dark.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/coupon.svg
    - assets/icon/upload.svg
    - assets/icon/map-marker.svg
    - assets/icon/tokopedia.svg
    - assets/icon/shopee.svg
    - assets/icon/twitter.svg
    - assets/icon/facebook.svg
    - assets/icon/google.svg
    - assets/icon/check.svg
    - assets/icon/uncheck.svg
    - assets/icon/back.svg
    - assets/icon/menu.svg
    - assets/splashscreen/logo.png
    - assets/icon/bell-Bold.svg
    - assets/icon/news.png
    - assets/icon/transport.png
    - assets/icon/umkm.png
    - assets/icon/wisata.png
    - assets/splashscreen/image6.png
    - assets/splashscreen/image1.webp
    - assets/splashscreen/logo_dark.png
    - assets/splashscreen/map.jpg
    - assets/icon/bell.svg
    - assets/icon/star.svg
    - assets/icon/star_outline.svg
    - assets/icon/map.svg
    - assets/icon/search.svg
