include: package:flutter_lints/flutter.yaml
<<<<<<< HEAD

=======
linter:
  rules:
    depend_on_referenced_packages: false
>>>>>>> 95f5e7c4b2f337e1d1902841f661930ffa66dee2
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
