name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl:

  theme:
    path: ../theme

  loading_animation_widget:
  cached_network_image:
  flutter_bloc:
  get_it:
  flutter_svg:
  equatable:
  carousel_slider: ^4.1.1
  page_transition: ^2.0.9
  flutter_native_splash: ^2.2.3+1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - ../assets/icon/bold/
    - ../assets/icon/fill/
    - ../assets/icon/regular/
    - ../assets/icon/light/
    - ../assets/icon/menu/
    - ../assets/splashscreen/
    - ../assets/image/
    - ../assets/logo/
    - ../assets/icon/coupon.svg
    - ../assets/icon/upload.svg
    - ../assets/icon/map-marker.svg
    - ../assets/icon/tokopedia.svg
    - ../assets/icon/shopee.svg
    - ../assets/icon/twitter.svg
    - ../assets/icon/facebook.svg
    - ../assets/icon/google.svg
    - ../assets/icon/check.svg
    - ../assets/icon/uncheck.svg
    - ../assets/icon/back.svg
    - ../assets/icon/menu.svg
    - ../assets/icon/cross.svg
    - ../assets/icon/user_outline.svg
    - ../assets/icon/user.svg
    - ../assets/icon/star_outline.svg
    - ../assets/icon/star.svg
    - ../assets/icon/home_outline.svg
    - ../assets/icon/home.svg
    - ../assets/icon/copy_outline.svg
    - ../assets/icon/copy.svg
    - ../assets/icon/lock.svg
    - ../assets/icon/eye.svg
    - ../assets/icon/eye-slash.svg
    - ../assets/icon/envelope.svg
    - ../assets/icon/envelope-fill.svg
    - ../assets/icon/pen.svg
    - ../assets/icon/pen-Light.svg
    - ../assets/icon/shield.svg
    - ../assets/icon/check-circle.svg
    - ../assets/icon/file.svg
    - ../assets/icon/bell.svg
    - ../assets/icon/bell-Light.svg
    - ../assets/icon/trash-Light.svg
    - ../assets/icon/camera-Light.svg
    - ../assets/icon/info-circle.svg
    - ../assets/icon/question-circle.svg
    - ../assets/icon/plus-circle.svg
    - ../assets/icon/settings.svg
    - ../assets/icon/globe.svg
    - ../assets/icon/mode.svg
    - ../assets/icon/log-out.svg
    - ../assets/icon/chevron-right.svg
    - ../assets/icon/bell-Bold.svg
    - ../assets/icon/news.png
    - ../assets/icon/transport.png
    - ../assets/icon/umkm.png
    - ../assets/icon/wisata.png
    - ../assets/icon/bell.svg
    - ../assets/icon/star.svg
    - ../assets/icon/star_outline.svg
    - ../assets/icon/map.svg
    - ../assets/icon/search.svg
