name: account
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  theme:
    path: ../theme
  news:
    path: ../news
  core:
    path: ../core
  transportation:
    path: ../transportation

  firebase_auth:
  google_sign_in:
  flutter_facebook_auth:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_analytics:
  shared_preferences:
  dartz:
  flutter_bloc:
  equatable:
  flutter_svg:
  flutter_slidable: 
  cached_network_image:
  page_transition:
  loading_animation_widget:
  fluttertoast: 
  image_picker:
  path: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - ../assets/icon/bold/
    - ../assets/icon/fill/
    - ../assets/icon/regular/
    - ../assets/icon/light/
    - ../assets/icon/menu/
    - ../assets/splashscreen/
    - ../assets/image/
    - ../assets/logo/
    - ../assets/icon/coupon.svg
    - ../assets/icon/upload.svg
    - ../assets/icon/map-marker.svg
    - ../assets/icon/tokopedia.svg
    - ../assets/icon/shopee.svg
    - ../assets/icon/twitter.svg
    - ../assets/icon/facebook.svg
    - ../assets/icon/google.svg
    - ../assets/icon/check.svg
    - ../assets/icon/uncheck.svg
    - ../assets/icon/back.svg
    - ../assets/icon/menu.svg
    - ../assets/icon/cross.svg
    - ../assets/icon/user_outline.svg
    - ../assets/icon/user.svg
    - ../assets/icon/star_outline.svg
    - ../assets/icon/star.svg
    - ../assets/icon/home_outline.svg
    - ../assets/icon/home.svg
    - ../assets/icon/copy_outline.svg
    - ../assets/icon/copy.svg
    - ../assets/icon/lock.svg
    - ../assets/icon/eye.svg
    - ../assets/icon/eye-slash.svg
    - ../assets/icon/envelope.svg
    - ../assets/icon/envelope-fill.svg
    - ../assets/icon/pen.svg
    - ../assets/icon/pen-Light.svg
    - ../assets/icon/shield.svg
    - ../assets/icon/check-circle.svg
    - ../assets/icon/file.svg
    - ../assets/icon/bell.svg
    - ../assets/icon/bell-Light.svg
    - ../assets/icon/trash-Light.svg
    - ../assets/icon/camera-Light.svg
    - ../assets/icon/info-circle.svg
    - ../assets/icon/question-circle.svg
    - ../assets/icon/plus-circle.svg
    - ../assets/icon/settings.svg
    - ../assets/icon/globe.svg
    - ../assets/icon/mode.svg
    - ../assets/icon/log-out.svg
    - ../assets/icon/chevron-right.svg
    - ../assets/icon/bell-Bold.svg
    - ../assets/icon/news.png
    - ../assets/icon/transport.png
    - ../assets/icon/umkm.png
    - ../assets/icon/wisata.png
    - ../assets/icon/bell.svg
    - ../assets/icon/star.svg
    - ../assets/icon/star_outline.svg
    - ../assets/icon/map.svg
    - ../assets/icon/search.svg
