name: transportation
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  theme:
    path: ../theme
  account:
    path: ../account
  umkm:
    path: ../umkm
  core:
    path: ../core

  intl:
  photo_view:
  flutter_bloc:
  flutter_svg:
  equatable:
  timelines:
  page_transition:
  loading_animation_widget:
  cached_network_image: 
  pull_to_refresh: 
  carousel_slider: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  
